name: CD

on:
  [workflow_dispatch, push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: add_checkout
        uses: actions/checkout@v4

      - name: check_PEP8
        shell: bash
        run: |
         pip install -r requirements.txt
         flake8 --exclude .git,.github .
